name: Troubleshooting Help
description: If you need troubleshooting help please use the troubleshooting form here: https://github.com/turtlebot/turtlebot4/issues/new/choose.
labels: ["troubleshooting"]
assignees:
  - hilary-luo
body:
  - type: markdown
    attributes:
      value: "If you need troubleshooting help please use the troubleshooting form here: https://github.com/turtlebot/turtlebot4/issues/new/choose."
